### ISSUE TITLE
Project not building

### ISSUE THREAD

**Issue by BobyIlea** [KAMIKAZEUA/SpriteBuilderX#2]
Hi, I am trying to build default branch SBX_UX in Xcode 11.0 and OS Catalina.

I got the following error:
```
rake aborted!
SyntaxError: /Users/Boby/Workspace/SpriteBuilderX/scripts/Rakefile:124: syntax error, unexpected '{', expecting end
...ed/#{TEMPLATE_FILENAME}.zip"] {}
...                              ^
/Users/Boby/Workspace/SpriteBuilderX/scripts/Rakefile:134: syntax error, unexpected end, expecting end-of-input
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
Command PhaseScriptExecution failed with a nonzero exit code
```
which I fixed by removing the {} at the end of the line 124 in Rakefile, but now I'm getting another build error: ld: library not found for -lcocos2d-mac
More details:
```
Ld /Users/Boby/Library/Developer/Xcode/DerivedData/SpriteBuilderX-boauelgohcktfiaxssszhgsdqser/Build/Products/Release/SpriteBuilderX.app/Contents/MacOS/SpriteBuilderX normal x86_64 (in target 'SpriteBuilderX' from project 'SpriteBuilderX')
    cd /Users/Boby/Workspace/SpriteBuilderX/SpriteBuilder
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/Boby/Library/Developer/Xcode/DerivedData/SpriteBuilderX-boauelgohcktfiaxssszhgsdqser/Build/Products/Release -L/Users/Boby/Workspace/SpriteBuilderX/SpriteBuilder/libs/Tupac -L/Users/Boby/Workspace/SpriteBuilderX/SpriteBuilder/libs/PVRTexTool -L/Users/Boby/Workspace/SpriteBuilderX/SpriteBuilder/libs/TextureConverter -F/Users/Boby/Library/Developer/Xcode/DerivedData/SpriteBuilderX-boauelgohcktfiaxssszhgsdqser/Build/Products/Release -Flibs -F/Users/Boby/Workspace/SpriteBuilderX/SpriteBuilder -filelist /Users/Boby/Library/Developer/Xcode/DerivedData/SpriteBuilderX-boauelgohcktfiaxssszhgsdqser/Build/Intermediates.noindex/SpriteBuilderX.build/Release/SpriteBuilderX.build/Objects-normal/x86_64/SpriteBuilderX.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/Boby/Library/Developer/Xcode/DerivedData/SpriteBuilderX-boauelgohcktfiaxssszhgsdqser/Build/Intermediates.noindex/SpriteBuilderX.build/Release/SpriteBuilderX.build/Objects-normal/x86_64/SpriteBuilderX_lto.o -fobjc-arc -fobjc-link-runtime -all_load -framework CoreFoundation -lcocos2d-mac -framework GLKit -lPVRTexLib -framework WebKit -framework CoreMedia -framework Security -framework SystemConfiguration -lTextureConverter -framework AVFoundation -framework OpenAL -framework AudioToolbox -framework Carbon -lffi -framework Quartz -framework ExceptionHandling -lz -framework OpenGL -framework QuartzCore -framework ApplicationServices -framework Cocoa -Xlinker -dependency_info -Xlinker /Users/Boby/Library/Developer/Xcode/DerivedData/SpriteBuilderX-boauelgohcktfiaxssszhgsdqser/Build/Intermediates.noindex/SpriteBuilderX.build/Release/SpriteBuilderX.build/Objects-normal/x86_64/SpriteBuilderX_dependency_info.dat -o /Users/Boby/Library/Developer/Xcode/DerivedData/SpriteBuilderX-boauelgohcktfiaxssszhgsdqser/Build/Products/Release/SpriteBuilderX.app/Contents/MacOS/SpriteBuilderX

ld: library not found for -lcocos2d-mac
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by BobyIlea** [comment]
Nevermind the second error, it worked after doing a clean build folder, not exactly sure why. But still, maybe the first fix that I've mentioned should be pushed to repo.

**Comment by KAMIKAZEUA** [comment]
This project wasn’t supported for a long time. Don’t expect all properly working here.

**Comment by BobyIlea** [comment]
@KAMIKAZEUA yeah I know, but since Cocos Studio is not running on Mac anymore I started to search for an alternative, and this might be a good starting point(although a cross-platform solution might be better). I'll play with it for a few days and if I find any more bugs and manage to fix them I'll create a pull request and let you know.

**Comment by KAMIKAZEUA** [comment]
The “problem” of this editor - it’s using custom cocos with a lot of own fixes and official patches. As I remember its trying to match 3.16 as in terms of fixes and modifications.
I’ve launched game using it with millions of downloads and I can confirm - it’s stable.

**Comment by KAMIKAZEUA** [comment]
However, I don’t see this as future. 
That Metal support for cocos is a huge task, they try it but just releasing something to test on us. The problem these days there are not so much us left for this testing.
Yes, this open source and quality it’s just a people who use it and report bugs, I see the big problem - these people are 0 now, really. 
I’m suggesting you to move some other engine.

**Comment by BobyIlea** [comment]
@KAMIKAZEUA Your points are correct and I've also already started investigating Godot engine, which looks very promising(good editor, C++ based, open source etc.). However, I'm currently involved in some big projects that heavily rely on Cocos Studio for levels/UI editing and most of the animations. So, at this point I'm not searching for an all-in-one engine solution such as Godot, Unreal or Unity, but I'm more in the search of a  scene editor. I don't want to publish games from SpriteBuilder, I only want to use it to publish resources. If I would manage to make it export resources in the same format as Cocos Studio did, that would be ideal for me, as I would be able to continue creating new content for my projects without any code change. At this point, I think that migrating existing code to Godot or Unreal is much more expensive for me than creating a tool that can do exactly what Cocos Studio used to.

**Comment by BobyIlea** [comment]
And yes, for new projects I will most probably be moving away from cocos2d-x, unfortunately, but my main concern now is the future of the already existing ones that need to be maintained  and updated with new content on a weekly basis.

**Comment by KAMIKAZEUA** [comment]
>  I don't want to publish games from SpriteBuilder, I only want to use it to publish resources.
This words make no sense. There is no such thing as "publish games from".

**Comment by BobyIlea** [comment]
I mean I don't think I need the custom cocos2d-x framework that is needed for resources exported from SpriteBuilderX. As long as I have my resources exported I can write my own code to import them at runtime. Ideally I will manage to export them in the same format as Cocos Studio did so I can just use the CSLoader class in code. I don't think this would be hard to do, though I'm not sure about the animation system...

**Comment by KAMIKAZEUA** [comment]
Thats basically you will create the same another wheel, same as SBLoader class doing already, but it's rely on custom cocos2dx, but again because without changing cocos2dx engine code it's impossible to load anything, like Button or something else. So, you'd need to modify cocos too and again in the same way as it's already beed modified for loader with custom version of it.

**Comment by KAMIKAZEUA** [comment]
Also, you probably already saw that cocos2d-x forum is a toxic place. There is only 1 moderator, and he thinks he has a crown on his head. Thats just fact. All posts and topics about future of C++ was removed and closed( like this https://discuss.cocos2d-x.org/t/we-need-a-friendly-engine-not-a-dysfunction-editor/33651  ), they interested only in china crap quality cocos creator. That product just crap. They never know how to develop a good editor, thats just their mentality. 
Before that, in cocos2dx devs there were are lot of US and EU devs, their way of thinking, implementing features and thinking was helping a lot to be stable

**Comment by KAMIKAZEUA** [comment]
So, finally I'd recommend to start to move to unity, there is no other options. 
When you downloading SDK from any company, it's just has 3 types of it: 
 - iOS native
 - android native
 - unity

Think about it, why there is no other engine's SDK...

**Comment by BobyIlea** [comment]
Yes, I agree, I'm also a big advocate of C++ on that forum and I also don't like Cocos Creator, it just doesn't make sense to me. cocos2d-x was such a successful engine because it was lightweight, fast(being C++ based), flexible(because it's open source) and easily extendable. But all of these good points are missing from Creator. Maybe most of people use cocos2d-x for small games, but I use it for some very large projects. It is impossible to use Creator for a medium or large project. I also stated all these points many times on the 2d-x forums(you can check my posts there under the username Boby) and everytime they said that they are still planning to support 2d-x, but I'm not really sure that's true.

**Comment by BobyIlea** [comment]
I've also considered switching to Unity for future projects but I don't think I will. Mostly because it's not open-source which means I'm dependent on the Unity team to release updates and fix bugs, which sometimes takes a lot of time(I know a few people who waited for months before Unity pushed a fix to a crashing bug in their engine and because of that they lost a lot of users - mostly due to the new Android Vitals thing). Second of all, we have a lot of C++ code that would be hard to port to C#(I don't even want to start thinking about the different memory management system). Because of this a better choice would be Unreal engine(C++, open source but not very good 2D tools) or Godot(C++, open source, good 2d tools, but they don't support C++ 11 and STL yet).

As for external SDKs, yes everyone has an iOS native and Android Native SDK, but integrating those SDKs in a cocos2d-x game is almost trivial. We use a lot of external SDKs(ads, analytics, engagement etc.) in our cocos2d-x games and it's never been a problem for us to integrate native code into 2d-x projects.

**Comment by KAMIKAZEUA** [comment]
I think cocos2dx will be dead fully after Metal will be only thing, who will test all that bunch of code added to fix for some way to make it work? You will throw game into production phase with such? 

Also take into account that when slackmoehrle writes "we", thats basically only him. Some developers in china will never read what you said and they don't care at all.

**Comment by BobyIlea** [comment]
> I think cocos2dx will be dead fully after Metal will be only thing, who will test all that bunch of code added to fix for some way to make it work? You will throw game into production phase with such?

Well in some cases we don't really have a choice. For some big projects which have been developed for years now, porting them to another engine will be a real pain, I'm talking about a work that could take up an entire year or so. In this case it might be better to just wait for the metal support and see if it works or not...

**Comment by KAMIKAZEUA** [comment]
So just add to that entire year more that time of hope :) of quality.

**Comment by BobyIlea** [comment]
Yeah, that's the risk I guess. But the good part is that having access to the sources, even if the Cocos team does not do a good job, we can always fix some issues ourselves, like we did in the past. Of course, it depends on how many issues the new version will have.

Another possible idea would be to take the current state of cocos2d-x and create a new community-driven project... but that's risky as well, most people nowdays just want out of the box solutions. That's because of the current state of the gaming industry, let's be honest, it's more important to release as many games as possible even if they are not high quality than to spend much time on polishing a great product... this is why solutions such as Cocos Creator are gaining so much momentum right now...
